USE study_match_db;

-- Add new profile fields to users table
ALTER TABLE users 
ADD COLUMN pronouns VARCHAR(50) DEFAULT NULL,
ADD COLUMN gender VARCHAR(50) DEFAULT NULL,
ADD COLUMN study_goal VARCHAR(255) DEFAULT NULL,
ADD COLUMN looking_for VARCHAR(255) DEFAULT NULL,
ADD COLUMN study_style VARCHAR(255) DEFAULT NULL,
ADD COLUMN study_time VARCHAR(255) DEFAULT NULL,
ADD COLUMN study_location VARCHAR(255) DEFAULT NULL,
ADD COLUMN study_vibe VARCHAR(255) DEFAULT NULL,
ADD COLUMN strength VARCHAR(255) DEFAULT NULL,
ADD COLUMN weakness VARCHAR(255) DEFAULT NULL;
